// app.js - drives the Progressive Automation Harness UI against the FastAPI backend.

const $ = (id) => document.getElementById(id);
const api = (path, opts) =>
  fetch(path, { headers: { "Content-Type": "application/json" }, ...opts }).then(
    async (r) => {
      if (!r.ok) throw new Error((await r.json().catch(() => ({}))).detail || r.statusText);
      return r.json();
    }
  );

let state = {
  demo: null,
  schema: null,
  sessionId: null,
  taskName: "",
  detail: "balanced",
  model: "auto",
  mode: "describe",
  interviewId: null,
};

// ---------- helpers ----------
function toast(msg, ms = 2600) {
  const t = $("toast");
  t.textContent = msg;
  t.hidden = false;
  clearTimeout(toast._t);
  toast._t = setTimeout(() => (t.hidden = true), ms);
}

function sourceBadge(source) {
  if (!source) return "";
  if (source.startsWith("skill")) return `<span class="badge skill">${source}</span>`;
  if (source === "llm") return `<span class="badge llm">llm</span>`;
  return `<span class="badge mock">${source}</span>`;
}

function busy(btn, on, label) {
  if (!btn) return;
  if (on) {
    btn.dataset.label = btn.innerHTML;
    btn.disabled = true;
    btn.innerHTML = `<span class="spin">◐</span> ${label || "Working…"}`;
  } else {
    btn.disabled = false;
    btn.innerHTML = btn.dataset.label || btn.innerHTML;
  }
}

// ---------- mode / health ----------
async function loadHealth() {
  try {
    const h = await api("/api/health");
    $("modeDot").className = "dot " + (h.offline ? "offline" : "online");
    $("modeText").textContent = h.offline ? "offline · mock drafts" : "live · Azure gpt-5.6-sol";
  } catch {
    $("modeText").textContent = "backend offline";
  }
}

// ---------- generate ----------
function renderPreview(schema, by, model) {
  state.schema = schema;
  state.taskName = schema.task_name;
  $("previewTask").textContent = schema.task_name;
  $("previewBy").textContent = model ? `${by || "demo"} · ${model}` : (by || "demo");
  $("previewSteps").innerHTML = schema.steps
    .map((s) => `<li><b>${s.name}</b>: ${s.description}</li>`)
    .join("");
  $("preview").hidden = false;
  // Reflect this task's learned skill (if any) in the Skill panel.
  loadSkillReport(schema.task_name);
}

async function generate() {
  const desc = $("desc").value.trim();
  if (!desc) {
    toast("Describe a task first, or pick a demo chip.");
    return;
  }
  busy($("generateBtn"), true, "Generating…");
  try {
    const res = await api("/api/generate", {
      method: "POST",
      body: JSON.stringify({ description: desc, detail: state.detail, model: state.model }),
    });
    renderPreview(res.schema, res.generated_by, res.model);
    toast(res.generated_by === "llm" ? "Workflow generated by the LLM." : "Used a demo workflow.");
  } catch (e) {
    toast("Generate failed: " + e.message);
  } finally {
    busy($("generateBtn"), false);
  }
}

// ---------- session ----------
async function ensureSchema() {
  if (state.schema) return state.schema;
  // Require an explicit selection: a picked example fills the box, or the user
  // typed a task. No implicit default, so nothing runs without a real choice.
  const typed = $("desc").value.trim();
  if (!typed) {
    toast("Pick an example or describe a task first.");
    return null;
  }
  const res = await api("/api/generate", {
    method: "POST",
    body: JSON.stringify({ description: typed, detail: state.detail, model: state.model }),
  });
  renderPreview(res.schema, res.generated_by, res.model);
  return res.schema;
}

async function startSession() {
  if (state.mode === "interview" && !state.schema) {
    toast("Answer a few questions first, or switch to Quick describe.");
    return;
  }
  busy($("startBtn"), true, "Planning…");
  try {
    const schema = await ensureSchema();
    if (!schema) return; // no selection yet; ensureSchema already prompted
    // Surface the grounded plan before stepping through it.
    busy($("startBtn"), false);
    busy($("startBtn"), true, "Starting…");
    const view = await api("/api/session", {
      method: "POST",
      body: JSON.stringify({
        workflow: schema,
        inputs: readRunInputs(),
        model: state.model,
        require_approvals: $("nyesToggle") && $("nyesToggle").checked ? 2 : 1,
      }),
    });
    state.sessionId = view.session_id;
    $("emptyStage").hidden = true;
    render(view);
    toast(`Plan ready: ${schema.steps.length} step(s). Co-pilot started.`);
  } catch (e) {
    toast("Start failed: " + e.message);
  } finally {
    busy($("startBtn"), false);
  }
}

async function decide(decision) {
  const feedback = $("feedback").value.trim();
  document.querySelectorAll(".bp-actions .btn").forEach((b) => (b.disabled = true));
  try {
    const view = await api(`/api/session/${state.sessionId}/decision`, {
      method: "POST",
      body: JSON.stringify({ decision, feedback }),
    });
    $("feedback").value = "";
    render(view);
  } catch (e) {
    toast("Decision failed: " + e.message);
    document.querySelectorAll(".bp-actions .btn").forEach((b) => (b.disabled = false));
  }
}

// Run a human-edited action verbatim; the edit becomes the learned exemplar.
async function editAndRun() {
  const action = $("editAction").value.trim();
  if (!action) {
    toast("Edit the action text first, then Edit & run.");
    return;
  }
  document.querySelectorAll(".bp-actions .btn").forEach((b) => (b.disabled = true));
  try {
    const view = await api(`/api/session/${state.sessionId}/decision`, {
      method: "POST",
      body: JSON.stringify({ decision: "edit", action }),
    });
    render(view);
  } catch (e) {
    toast("Edit failed: " + e.message);
    document.querySelectorAll(".bp-actions .btn").forEach((b) => (b.disabled = false));
  }
}

// ---------- rendering ----------
function render(view) {
  state.taskName = view.task_name;
  renderTimeline(view.history);
  renderBreakpoint(view);
  renderSkill(view.skill);
  $("doneBanner").hidden = !view.completed;
  if (view.completed) toast("Workflow complete. Skill updated.");
}

function renderTimeline(history) {
  const tl = $("timeline");
  tl.hidden = false;
  tl.innerHTML = (history || [])
    .map((e) => {
      if (e.event === "draft") {
        return `<div class="event draft">
          <div class="ev-head">✎ Drafted · step ${e.step_index + 1} · ${e.step_name} ${sourceBadge(e.source)}</div>
          <div class="ev-body">${escapeHtml(e.action)}</div>
        </div>`;
      }
      if (e.event === "human_review") {
        return `<div class="event review">
          <div class="ev-head">🙦 Reviewed <span class="badge ${e.decision}">${e.decision}</span></div>
          ${e.feedback ? `<div class="ev-body muted">“${escapeHtml(e.feedback)}”</div>` : ""}
        </div>`;
      }
      if (e.event === "execute") {
        const r = e.result || "";
        let toolBadge = "";
        if (r.startsWith("[mcp:")) {
          const m = r.match(/^\[mcp:([^\]]+)\]/);
          toolBadge = `<span class="badge mcp">mcp · ${m ? m[1] : ""}</span>`;
        } else if (r.startsWith("[browsed")) {
          toolBadge = `<span class="badge web">web</span>`;
        }
        return `<div class="event execute">
          <div class="ev-head">⚡ Executed · ${e.step_name} ${toolBadge}</div>
          <div class="ev-body">${escapeHtml(r)}</div>
        </div>`;
      }
      return "";
    })
    .join("");
  tl.scrollIntoView({ behavior: "smooth", block: "end" });
}

function renderBreakpoint(view) {
  const bp = $("breakpoint");
  if (view.status !== "awaiting_review") {
    bp.hidden = true;
    return;
  }
  const idx = view.current_step_index;
  const step = view.steps[idx];
  $("bpStep").textContent = `Step ${idx + 1} of ${view.steps.length} · ${step ? step.name : ""}`;
  $("bpAction").textContent = deDash(view.drafted_action || "");
  $("editAction").value = deDash(view.drafted_action || "");
  $("bpSource").innerHTML = sourceBadge(view.draft_source);
  // N-eyes: show co-approval status when a step needs more than one approver.
  const appr = view.approval || { required: 1, have: 0 };
  const bpAppr = $("bpApproval");
  if (bpAppr) {
    if (appr.required > 1) {
      bpAppr.hidden = false;
      bpAppr.textContent =
        `🔐 Segregation of duties: needs ${appr.required} distinct approvers ` +
        `(${appr.have}/${appr.required} so far` +
        (appr.teams ? " · Teams notified)" : ")");
    } else {
      bpAppr.hidden = true;
    }
  }
  document.querySelectorAll(".bp-actions .btn").forEach((b) => (b.disabled = false));
  bp.hidden = false;
}

// Skill-panel action buttons only work once a skill exists for the current task.
const SKILL_ACTION_IDS = ["viewJsonBtn", "promptBtn", "exportBtn", "deployBtn", "runBtn", "runInputs"];

function setSkillActionsEnabled(on) {
  SKILL_ACTION_IDS.forEach((id) => {
    const el = $(id);
    if (el) el.disabled = !on;
  });
}

// Neutral state: no task chosen yet in panel 1, so the Skill panel is generic.
function resetSkillPanel() {
  state.taskName = "";
  const badge = $("overallBadge");
  badge.textContent = "—";
  badge.dataset.level = "";
  document.querySelectorAll(".rung").forEach((r) => r.classList.remove("reached"));
  $("skillRows").innerHTML =
    `<p class="muted small">Describe a task and click Start to watch the skill form here.</p>`;
  setSkillActionsEnabled(false);
}

// Load and render the current task's learned skill (dynamic per selection).
async function loadSkillReport(name) {
  if (!name) return;
  try {
    const res = await api(`/api/skill-report?name=${encodeURIComponent(name)}`);
    renderSkill({ rows: res.rows, overall: res.overall });
  } catch (e) {
    renderSkill({ rows: [], overall: "cold" });
  }
}

// Clear all state and return the UI to a fresh, unselected session.
function newSession() {
  state.sessionId = null;
  state.schema = null;
  state.interviewId = null;
  state.demo = null;
  const desc = $("desc");
  if (desc) desc.value = "";  document.querySelectorAll(".chip").forEach((c) => c.classList.remove("active"));
  ["preview", "breakpoint", "doneBanner"].forEach((id) => {
    const el = $(id);
    if (el) el.hidden = true;
  });
  const stage = $("emptyStage");
  if (stage) stage.hidden = false;
  const tl = $("timeline");
  if (tl) {
    tl.innerHTML = "";
    tl.hidden = true;
  }
  const chat = $("chatLog");
  if (chat) chat.innerHTML = "";
  resetSkillPanel();
  setMode("describe");
  toast("New session — everything cleared.");
}

function renderSkill(skill) {
  const overall = (skill && skill.overall) || "cold";
  const badge = $("overallBadge");
  badge.textContent = overall;
  badge.dataset.level = overall;
  const order = ["cold", "primed", "deterministic", "autonomous"];
  const reachedIdx = order.indexOf(overall);
  document.querySelectorAll(".rung").forEach((r) => {
    r.classList.toggle("reached", order.indexOf(r.dataset.level) <= reachedIdx);
  });

  const rows = (skill && skill.rows) || [];
  const box = $("skillRows");
  setSkillActionsEnabled(rows.length > 0);
  if (!rows.length) {
    box.innerHTML = `<p class="muted small">No skill learned yet for this task.</p>`;
    return;
  }
  const pct = { cold: 12, primed: 40, deterministic: 72, autonomous: 100 };
  box.innerHTML = rows
    .map(
      (r) => `<div class="srow">
        <span class="name">${r.step_id}. ${escapeHtml(r.step_name)}</span>
        <span class="meta">${r.approvals} approvals${
          r.rejections ? ` · ${r.rejections} rejected` : ""
        }${r.failures ? ` · ${r.failures} failed` : ""} · ${r.maturity}</span>
        <div class="prog"><i style="width:${pct[r.maturity] || 12}%"></i></div>
      </div>`
    )
    .join("");
}

// ---------- simulate ----------
async function simulate() {
  const task = $("simTask").value;
  const runs = parseInt($("simRuns").value, 10) || 6;
  busy($("simBtn"), true, "Simulating…");
  try {
    const res = await api("/api/simulate", {
      method: "POST",
      body: JSON.stringify({ task, runs }),
    });
    state.taskName = res.task_name;
    const last = res.progression[res.progression.length - 1];
    renderSkill(last);
    const climb = res.progression.map((p) => p.overall).join(" → ");
    toast(`${res.task_name}: ${climb}`, 5000);
  } catch (e) {
    toast("Simulate failed: " + e.message);
  } finally {
    busy($("simBtn"), false);
  }
}

// ---------- skill json ----------
async function viewJson() {
  if (!state.taskName) return toast("Pick or generate a workflow first.");
  try {
    const res = await api(`/api/skill-artifact?name=${encodeURIComponent(state.taskName)}`);
    $("jsonTitle").textContent = res.exists ? `${res.task_name} · skill.json` : "no skill yet";
    $("jsonBody").textContent = res.exists ? res.json : "// Run or simulate this workflow to compile a skill.";
    $("jsonModal").hidden = false;
  } catch (e) {
    toast("Could not load skill: " + e.message);
  }
}

async function viewPrompt() {
  if (!state.taskName) return toast("Pick or generate a workflow first.");
  try {
    const res = await api(`/api/skill-export?name=${encodeURIComponent(state.taskName)}`);
    $("jsonTitle").textContent = res.exists
      ? `${res.task_name} · portable prompt (paste into Claude or any LLM)`
      : "no skill yet";
    $("jsonBody").textContent = res.exists
      ? res.prompt
      : "// Run or simulate this workflow to compile a skill.";
    $("jsonModal").hidden = false;
  } catch (e) {
    toast("Could not load prompt: " + e.message);
  }
}

async function exportSkill() {
  if (!state.taskName) return toast("Pick or generate a workflow first.");
  try {
    const res = await api(`/api/skill-artifact?name=${encodeURIComponent(state.taskName)}`);
    if (!res.exists) {
      toast("No skill yet. Run or simulate this workflow first.");
      return;
    }
    const blob = new Blob([res.json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${res.task_name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}.skill.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast("Skill exported as JSON.");
  } catch (e) {
    toast("Export failed: " + e.message);
  }
}

async function deploySkill() {
  if (!state.taskName) return toast("Pick or generate a workflow first.");
  busy($("deployBtn"), true, "Deploying…");
  try {
    const res = await api(`/api/skill-deploy?name=${encodeURIComponent(state.taskName)}`, {
      method: "POST",
    });
    toast(
      `Published "${res.task_name}" (${res.overall}) to ${res.path}. Run it by ` +
        `starting a co-pilot session for this task, or use Prompt to run it in any LLM.`,
      7000
    );
  } catch (e) {
    toast("Deploy failed: " + e.message);
  } finally {
    busy($("deployBtn"), false);
  }
}

// Parse the optional "Inputs (JSON)" field; returns {} when empty/blank.
function readRunInputs() {
  const raw = ($("runInputs") && $("runInputs").value || "").trim();
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) return parsed;
    toast("Inputs must be a JSON object; ignoring.");
  } catch (e) {
    toast("Inputs JSON is invalid; ignoring. " + e.message);
  }
  return {};
}

async function runSkill() {
  if (!state.taskName) return toast("Pick or generate a workflow first.");
  busy($("runBtn"), true, "Running…");
  try {
    const inputs = readRunInputs();
    const res = await api(`/api/skill-run?name=${encodeURIComponent(state.taskName)}`, {
      method: "POST",
      body: JSON.stringify({ inputs }),
    });
    if (!res.ran && res.status !== "blocked") {
      toast(res.reason || "Nothing to run.");
      return;
    }
    if (res.status === "blocked") {
      toast(`Ran up to high-risk step "${res.blocked_step}". A human is required there.`, 7000);
    } else {
      toast(`Ran "${res.task_name}" headlessly: ${res.steps_executed} step(s) executed.`, 7000);
    }
  } catch (e) {
    toast("Run failed: " + e.message);
  } finally {
    busy($("runBtn"), false);
  }
}

// ---------- utils ----------
function deDash(s) {
  return (s || "").replace(/\s*[\u2014\u2013]\s*/g, ", ");
}

function escapeHtml(s) {
  return deDash(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

// ---------- interview ----------
function addBubble(role, text) {
  const log = $("chatLog");
  const div = document.createElement("div");
  div.className = `bubble ${role}`;
  div.textContent = deDash(text);
  log.appendChild(div);
  log.scrollTop = log.scrollHeight;
}

async function startInterview() {
  if (state.interviewId) return;
  $("chatLog").innerHTML = "";
  addBubble("assistant", "Thinking…");
  try {
    const res = await api("/api/interview/start", { method: "POST", body: "{}" });
    state.interviewId = res.interview_id;
    $("chatLog").lastChild.textContent = res.message;
  } catch (e) {
    $("chatLog").lastChild.textContent = "Could not start interview: " + e.message;
  }
}

async function sendChat() {
  const text = $("chatText").value.trim();
  if (!text || !state.interviewId) return;
  $("chatText").value = "";
  addBubble("user", text);
  addBubble("assistant", "Thinking…");
  try {
    const res = await api(`/api/interview/${state.interviewId}/message`, {
      method: "POST",
      body: JSON.stringify({ text, detail: state.detail }),
    });
    if (res.done) {
      $("chatLog").lastChild.textContent = "Great, I have enough. Compiling your plan…";
      renderPreview(res.schema, "interview");
      toast(`Plan ready: ${res.schema.steps.length} step(s). Click Start co-pilot.`, 5000);
    } else {
      $("chatLog").lastChild.textContent = res.message;
    }
  } catch (e) {
    $("chatLog").lastChild.textContent = "Error: " + e.message;
  }
}

function setMode(mode) {
  state.mode = mode;
  document.querySelectorAll(".mode-tab").forEach((t) =>
    t.classList.toggle("active", t.dataset.mode === mode)
  );
  $("describeMode").hidden = mode !== "describe";
  $("interviewMode").hidden = mode !== "interview";
  $("generateBtn").style.display = mode === "interview" ? "none" : "";
  if (mode === "interview") startInterview();
}

// ---------- MCP tools ----------
async function loadMcpTools() {  try {
    const res = await api("/api/mcp/tools", { method: "POST", body: "{}" });
    const box = $("mcpTools");
    const tools = (res.tools || []).filter((t) => t.name);
    $("mcpStatus").textContent = res.available
      ? `${tools.length} tool(s)`
      : "unavailable";
    if (!tools.length) {
      box.innerHTML = `<p class="muted small">No MCP tools discovered.</p>`;
      return;
    }
    box.innerHTML = tools
      .map(
        (t) => `<div class="mcp-tool">
          <div class="t-server">${escapeHtml(t.server)}</div>
          <div class="t-name">${escapeHtml(t.name)}</div>
          <div class="t-desc">${escapeHtml(t.description)}</div>
        </div>`
      )
      .join("");
  } catch (e) {
    $("mcpStatus").textContent = "error";
    $("mcpTools").innerHTML = `<p class="muted small">MCP discovery failed.</p>`;
  }
}

// ---------- models ----------
async function loadModels() {
  try {
    const res = await api("/api/models");
    const sel = $("modelSelect");
    const opts = ['<option value="auto">Auto (tiered by detail)</option>'];
    (res.models || []).forEach((m) => {
      const label = m === res.default ? `${m} (default)` : m;
      opts.push(`<option value="${m}">${label}</option>`);
    });
    sel.innerHTML = opts.join("");
    sel.value = state.model;
  } catch (e) {
    /* leave the Auto-only default in place */
  }
}

// Prove the deployed harness identity can build on real Fabric.
async function fabricSelftest() {
  const out = $("fabricTestResult");
  busy($("fabricTestBtn"), true, "Testing…");
  try {
    const res = await api("/api/fabric/selftest", { method: "POST", body: "{}" });
    out.hidden = false;
    out.textContent = res.enabled
      ? deDash(res.created || "Done.")
      : "Fabric isn't configured for this deployment.";
  } catch (e) {
    out.hidden = false;
    out.textContent = "Self-test failed: " + e.message;
  } finally {
    busy($("fabricTestBtn"), false);
  }
}

// ---------- library ----------
async function loadLibrary() {
  const grid = $("libGrid");
  try {
    const res = await api("/api/skills");
    const skills = res.skills || [];
    if (!skills.length) {
      grid.innerHTML = `
        <div class="lib-empty">
          <p class="muted small">No skills yet. Run a workflow in the Studio to compile one — or seed a few sample skills to explore the lifecycle.</p>
          <button class="btn primary tiny" id="seedSkillsBtn" title="Create demo skills spanning lifecycle states">✨ Seed demo skills</button>
        </div>`;
      const sb = $("seedSkillsBtn");
      if (sb) sb.addEventListener("click", seedDemoSkills);
    } else {
      grid.innerHTML = skills
        .map((s) => {
          const inputs = (s.required_inputs || []).length
            ? `<div class="lib-inputs">inputs: ${s.required_inputs.map(escapeHtml).join(", ")}</div>`
            : "";
          return `<div class="lib-card" data-name="${escapeHtml(s.task_name)}">
            <div class="lib-card-top">
              <span class="mat-badge" data-level="${s.overall}">${s.overall}</span>
              <span class="status-badge" data-state="${s.display || "draft"}">${statusLabel(s.display)}</span>
            </div>
            <h3>${escapeHtml(s.task_name)}</h3>
            <p class="lib-summary">${escapeHtml(s.summary || "No summary.")}</p>
            ${inputs}
            <div class="lib-meta">v${s.version || 1} \u00b7 ${s.steps} step(s) \u00b7 ${s.approvals} approval(s)</div>
            <div class="lib-actions">
              <button class="btn primary tiny" data-open="${escapeHtml(s.task_name)}" title="Open this skill in the Studio">Open in Studio \u2192</button>
              <button class="btn ghost tiny" data-run="${escapeHtml(s.task_name)}" title="Watch this skill execute step by step">\u25b6 Watch it run</button>
              <button class="btn ghost tiny" data-life="${escapeHtml(s.task_name)}" title="Manage this skill's lifecycle">\u26ed Lifecycle</button>
            </div>
          </div>`;
        })
        .join("");
      grid.querySelectorAll("[data-open]").forEach((b) =>
        b.addEventListener("click", () => openSkill(b.dataset.open))
      );
      grid.querySelectorAll("[data-run]").forEach((b) =>
        b.addEventListener("click", () => openRunner(b.dataset.run))
      );
      grid.querySelectorAll("[data-life]").forEach((b) =>
        b.addEventListener("click", () => openLifecycle(b.dataset.life))
      );
    }
  } catch (e) {
    grid.innerHTML = `<p class="muted small">Could not load the library: ${escapeHtml(e.message)}</p>`;
  }
  loadShellTool();
}

// Open a library skill in the Studio: reflect it in the Skill panel so it can
// be inspected (JSON/Prompt), exported, or run headlessly.
function openSkill(name) {
  state.taskName = name;
  state.schema = null;
  loadSkillReport(name);
  setView("studio");
  toast(`Opened "${name}". Use JSON, Prompt, Export, or Run deployed skill.`, 4000);
}

// Create a spread of demo skills (different lifecycle states) with one click.
async function seedDemoSkills() {
  const btn = $("seedSkillsBtn");
  busy(btn, true, "Seeding\u2026");
  try {
    const res = await api("/api/skills/seed", { method: "POST", body: "{}" });
    toast(`Seeded ${res.count} demo skill(s).`);
    loadLibrary();
  } catch (e) {
    toast("Seeding failed: " + e.message, 5000);
  } finally {
    busy(btn, false);
  }
}

// ---------- skill lifecycle ----------
const STATUS_LABELS = {
  draft: "draft",
  in_training: "in training",
  candidate: "candidate",
  active: "active",
  needs_attention: "needs attention",
  deprecated: "deprecated",
  retired: "retired",
};
function statusLabel(state) {
  return STATUS_LABELS[state] || state || "draft";
}

async function openLifecycle(name) {
  if (!name) return;
  $("lifeTitle").textContent = `Lifecycle \u00b7 ${name}`;
  $("lifeBody").innerHTML = `<p class="muted small">Loading\u2026</p>`;
  $("lifecycleModal").hidden = false;
  try {
    const d = await api(`/api/skill-lifecycle?name=${encodeURIComponent(name)}`);
    if (!d.exists) {
      $("lifeBody").innerHTML = `<p class="muted small">No skill yet for \u201c${escapeHtml(name)}\u201d.</p>`;
      return;
    }
    renderLifecycle(d);
  } catch (e) {
    $("lifeBody").innerHTML = `<p class="muted small">Could not load lifecycle: ${escapeHtml(e.message)}</p>`;
  }
}

function gateItem(ok, label) {
  return `<div class="gate-item ${ok ? "ok" : "no"}"><span>${ok ? "\u2713" : "\u2717"}</span> ${escapeHtml(label)}</div>`;
}

function renderLifecycle(d) {
  const drifting = !!(d.drift && d.drift.drifting);
  const order = ["cold", "primed", "deterministic", "autonomous"];
  const mature = order.indexOf(d.overall) >= order.indexOf("deterministic");
  const path = ["draft", "in_training", "candidate", "active"];
  const cur = d.display;
  const stagesHtml = path
    .map((st) => {
      const reached =
        path.indexOf(cur) >= path.indexOf(st) ||
        (["needs_attention", "deprecated", "retired"].includes(cur) && st === "active");
      return `<div class="life-stage ${reached ? "on" : ""} ${cur === st ? "cur" : ""}">${statusLabel(st)}</div>`;
    })
    .join('<span class="life-arrow">\u2192</span>');

  const gates = `<div class="gate-list">
      ${gateItem(mature, "Mature enough (\u2265 deterministic)")}
      ${gateItem(!d.regressions, "No rejected or failed steps")}
      ${gateItem(!drifting, "No execution drift")}
    </div>`;

  const promoteDisabled = d.certified ? "" : "disabled";
  const promoteTitle = d.certified ? "Publish this skill" : "Meet the publish gate first";
  const btns = [];
  if (!["active", "deprecated", "retired"].includes(cur)) {
    btns.push(`<button class="btn primary tiny" data-act="promote" ${promoteDisabled} title="${promoteTitle}">\u25b2 Promote / Publish</button>`);
  }
  btns.push(`<button class="btn ghost tiny" data-act="certify" title="Record a validation timestamp">\u2714 Certify</button>`);
  if (["active", "needs_attention"].includes(cur)) {
    btns.push(`<button class="btn ghost tiny" data-act="deprecate" title="Mark superseded but still runnable">\u2913 Deprecate</button>`);
  }
  if (cur !== "retired") {
    btns.push(`<button class="btn ghost tiny" data-act="retire" title="Sunset: no longer runnable">\u29b8 Retire</button>`);
  }
  if (["deprecated", "retired"].includes(cur)) {
    btns.push(`<button class="btn ghost tiny" data-act="reactivate" title="Bring it back">\u21ba Reactivate</button>`);
  }

  const versions =
    (d.versions || [])
      .slice()
      .reverse()
      .map(
        (v) => `<div class="ver-row">
        <span class="ver-tag">v${v.version}</span>
        <span class="ver-meta">${escapeHtml((v.note || "").toString())}${v.overall ? " \u00b7 " + escapeHtml(v.overall) : ""}</span>
        <button class="btn ghost tiny" data-roll="${v.version}">\u21a9 Rollback</button>
      </div>`
      )
      .join("") || `<p class="muted small">No versions yet \u2014 publish to snapshot one.</p>`;

  const gateReasons = (d.gate_reasons || []).length
    ? `<p class="muted small">To publish: ${d.gate_reasons.map(escapeHtml).join("; ")}.</p>`
    : "";

  $("lifeBody").innerHTML = `
    <div class="life-head">
      <span class="status-badge big" data-state="${cur}">${statusLabel(cur)}</span>
      <span class="muted small">v${d.version} \u00b7 maturity ${escapeHtml(d.overall)}${d.owner ? " \u00b7 owner " + escapeHtml(d.owner) : ""}</span>
    </div>
    <div class="life-stages">${stagesHtml}</div>
    <h4 class="life-h">Publish gate</h4>
    ${gates}
    ${gateReasons}
    ${drifting ? `<p class="drift-warn">\u26a0 Drift detected \u2014 recent failure / rejection rate is up. The skill stays under supervision until it recovers.</p>` : ""}
    <h4 class="life-h">Actions</h4>
    <div class="life-actions">${btns.join("")}</div>
    <h4 class="life-h">Version history</h4>
    <div class="ver-list">${versions}</div>
    <p class="muted small">Rollback restores that version's learned content; later runs recompile from the approval log.</p>`;

  $("lifeBody").querySelectorAll("[data-act]").forEach((b) =>
    b.addEventListener("click", () => lifecycleAction(d.task_name, b.dataset.act))
  );
  $("lifeBody").querySelectorAll("[data-roll]").forEach((b) =>
    b.addEventListener("click", () => rollbackVersion(d.task_name, parseInt(b.dataset.roll, 10)))
  );
}

async function lifecycleAction(name, action) {
  try {
    const d = await api(`/api/skill-lifecycle?name=${encodeURIComponent(name)}`, {
      method: "POST",
      body: JSON.stringify({ action }),
    });
    renderLifecycle(d);
    toast(`${statusLabel(d.display)} \u2014 ${action} done.`);
  } catch (e) {
    toast(e.message, 5000);
  }
}

async function rollbackVersion(name, version) {
  try {
    const d = await api(`/api/skill-rollback?name=${encodeURIComponent(name)}`, {
      method: "POST",
      body: JSON.stringify({ version }),
    });
    renderLifecycle(d);
    toast(`Rolled back to v${version}.`);
  } catch (e) {
    toast(e.message, 5000);
  }
}

// ---------- skill runner (watch a deployed skill execute) ----------
async function openRunner(name) {
  if (!name) return toast("Pick or open a skill first.");
  state.runTask = name;
  state.runInputs = [];
  $("runTitle").textContent = `Run \u00b7 ${name}`;
  $("runMaturity").textContent = "\u2014";
  $("runMaturity").dataset.level = "";
  $("runSummary").textContent = "";
  $("runMeta").hidden = true;
  $("runModalInputs").value = "";
  $("runTimeline").innerHTML =
    `<p class="muted small">Click \u201cRun it\u201d to watch the skill execute step by step.</p>`;
  renderRunFields([]);
  $("runModal").hidden = false;
  // Load the skill's declared inputs so we can render a field per input.
  try {
    const rep = await api(`/api/skill-report?name=${encodeURIComponent(name)}`);
    if (rep.overall) {
      $("runMaturity").textContent = rep.overall;
      $("runMaturity").dataset.level = rep.overall;
    }
    renderRunFields(rep.required_inputs || []);
  } catch (e) {
    renderRunFields([]);
  }
}

// Render one labelled field per declared input; else show the raw JSON box + hint.
function renderRunFields(fields) {
  state.runInputs = fields || [];
  const box = $("runInputFields");
  const hint = $("runInputsHint");
  if (fields && fields.length) {
    box.hidden = false;
    box.innerHTML = fields
      .map(
        (f) => `<label class="run-field"><span>${escapeHtml(f)}</span>
          <input class="inputs-field run-arg" data-key="${escapeHtml(f)}" type="text" placeholder="${escapeHtml(f)}" /></label>`
      )
      .join("");
    $("runModalInputs").hidden = true;
    hint.hidden = true;
  } else {
    box.hidden = true;
    box.innerHTML = "";
    $("runModalInputs").hidden = false;
    hint.hidden = false;
    hint.textContent =
      'This skill declares no inputs, so it defaults to MSFT. To look up a specific stock, enter e.g. {"symbol":"MSFT"}.';
  }
}

// Build the inputs object from the labelled fields, or the raw JSON box.
function collectRunInputs() {
  const fields = state.runInputs || [];
  if (fields.length) {
    const obj = {};
    document.querySelectorAll("#runInputFields .run-arg").forEach((inp) => {
      const v = inp.value.trim();
      if (v) obj[inp.dataset.key] = v;
    });
    return obj;
  }
  return parseRunModalInputs();
}

function parseRunModalInputs() {
  const raw = ($("runModalInputs").value || "").trim();
  if (!raw) return {};
  try {
    const p = JSON.parse(raw);
    if (p && typeof p === "object" && !Array.isArray(p)) return p;
    toast("Inputs must be a JSON object; ignoring.");
  } catch (e) {
    toast("Inputs JSON is invalid; ignoring. " + e.message);
  }
  return {};
}

async function playRun() {
  const name = state.runTask;
  if (!name) return;
  const inputs = collectRunInputs();
  busy($("runPlayBtn"), true, "Running\u2026");
  const tl = $("runTimeline");
  tl.innerHTML = `<p class="muted small">Executing\u2026</p>`;
  try {
    const res = await api(`/api/skill-run?name=${encodeURIComponent(name)}`, {
      method: "POST",
      body: JSON.stringify({ inputs }),
    });
    if (!res.steps || (!res.steps.length && res.status !== "blocked")) {
      tl.innerHTML = `<p class="muted small">${escapeHtml(
        res.reason || "Nothing to run \u2014 deploy or run this skill first."
      )}</p>`;
      return;
    }
    $("runMaturity").textContent = res.overall || "\u2014";
    $("runMaturity").dataset.level = res.overall || "";
    $("runSummary").textContent = deDash(res.summary || "");
    $("runMeta").hidden = false;
    $("runMeta").innerHTML =
      `<span><b>${res.autonomous_steps}</b>/${res.total_steps} ran autonomously</span>` +
      `<span>status: <b>${escapeHtml(res.status)}</b></span>` +
      `<span><b>${res.steps_executed}</b> executed</span>`;
    renderRunSteps(res.steps, res, name);
  } catch (e) {
    tl.innerHTML = `<p class="muted small">Run failed: ${escapeHtml(e.message)}</p>`;
  } finally {
    busy($("runPlayBtn"), false);
  }
}

function runTag(step) {
  const tags = [];
  const src = step.source || "";
  if (src.startsWith("skill")) tags.push(`<span class="run-tag src-skill">${escapeHtml(src)}</span>`);
  else if (src) tags.push(`<span class="run-tag src-llm">${escapeHtml(src)}</span>`);
  if (step.tool) tags.push(`<span class="run-tag tool">${escapeHtml(step.tool)}</span>`);
  if (step.high_risk) tags.push(`<span class="run-tag risk">high-risk</span>`);
  return tags.join(" ");
}

function stepCard(step, idx) {
  const status = step.status || "success";
  const gate =
    status === "blocked"
      ? `<div class="run-gate"><button class="btn primary tiny" data-handoff="1">\u23f8 Needs a human \u2014 finish in the co-pilot \u2192</button></div>`
      : "";
  const result = step.result
    ? `<div class="run-result">${escapeHtml(step.result)}</div>`
    : status === "blocked"
    ? `<div class="run-result">Paused before execution \u2014 this step must be approved by a person.</div>`
    : "";
  return `<div class="run-step ${status}">
    <div class="run-step-head">
      <span class="run-step-num">${idx}</span>
      <span class="run-step-name">${escapeHtml(step.name)}</span>
      ${runTag(step)}
    </div>
    ${step.action ? `<div class="run-action">${escapeHtml(step.action)}</div>` : ""}
    ${result}
    ${gate}
  </div>`;
}

// Reveal steps one at a time so you can watch the skill "run".
function renderRunSteps(steps, res, name) {
  const tl = $("runTimeline");
  tl.innerHTML = "";
  let i = 0;
  const reveal = () => {
    if (i >= steps.length) return;
    const holder = document.createElement("div");
    holder.innerHTML = stepCard(steps[i], i + 1);
    const card = holder.firstElementChild;
    tl.appendChild(card);
    const hb = card.querySelector("[data-handoff]");
    if (hb) hb.addEventListener("click", () => handoffToCopilot(name, res.summary));
    tl.scrollTop = tl.scrollHeight;
    i += 1;
    setTimeout(reveal, 650);
  };
  reveal();
}

// A high-risk step can't run headless: load the skill into the co-pilot to finish.
function handoffToCopilot(name, summary) {
  $("runModal").hidden = true;
  setView("studio");
  state.taskName = name;
  state.schema = null;
  const desc = $("desc");
  if (desc) desc.value = summary || name;
  loadSkillReport(name);
  toast(`Loaded \u201c${name}\u201d into the co-pilot \u2014 click Start co-pilot to finish the high-risk step with approval.`, 6000);
}

// ---------- shell tool ----------
async function loadShellTool() {
  try {
    const st = await api("/api/shell/status");
    const badge = st.enabled
      ? `<span class="pill on">enabled</span>`
      : `<span class="pill off">disabled</span>`;
    $("shellStatus").innerHTML =
      `${badge} scripts dir <code>${escapeHtml(st.scripts_dir)}</code> · timeout ${st.timeout}s` +
      (st.enabled ? "" : ` · set <code>SHELL_TOOL_ENABLED=1</code> to run`);
    $("shellCmd").disabled = !st.enabled;
    $("shellRunBtn").disabled = !st.enabled;
    renderScripts(st.scripts || [], st.enabled);
  } catch (e) {
    $("shellStatus").textContent = "Shell tool status unavailable.";
  }
}

function renderScripts(scripts, enabled) {
  const box = $("scriptList");
  if (!scripts.length) {
    box.innerHTML = `<p class="muted small">No scripts found in the registry.</p>`;
    return;
  }
  box.innerHTML = scripts
    .map(
      (s) => `<div class="script-item">
        <code>${escapeHtml(s.name)}</code>
        <input class="script-args" data-script="${escapeHtml(s.name)}" type="text" placeholder="flags, e.g. -Name World" ${enabled ? "" : "disabled"} />
        <button class="btn ghost tiny" data-runscript="${escapeHtml(s.name)}" ${enabled ? "" : "disabled"}>▷ Invoke</button>
      </div>`
    )
    .join("");
  box.querySelectorAll("[data-runscript]").forEach((b) =>
    b.addEventListener("click", () => runScript(b.dataset.runscript))
  );
}

function showShellOut(res) {
  const out = $("shellOut");
  out.hidden = false;
  if (res.error) {
    out.textContent = `✗ ${res.error}`;
    return;
  }
  const head = `$ ${res.command}\n(exit ${res.exit_code})`;
  const body = (res.stdout || res.stderr || "(no output)").trimEnd();
  out.textContent = `${head}\n\n${body}`;
}

async function runShellCommand() {
  const command = $("shellCmd").value.trim();
  if (!command) return toast("Type a command first.");
  busy($("shellRunBtn"), true, "Running…");
  try {
    const res = await api("/api/shell/run", {
      method: "POST",
      body: JSON.stringify({ command }),
    });
    showShellOut(res);
  } catch (e) {
    toast("Command failed: " + e.message);
  } finally {
    busy($("shellRunBtn"), false);
  }
}

async function runScript(name) {
  const field = document.querySelector(`.script-args[data-script="${CSS.escape(name)}"]`);
  const raw = (field && field.value.trim()) || "";
  const args = raw ? raw.split(/\s+/) : [];
  try {
    const res = await api("/api/shell/script", {
      method: "POST",
      body: JSON.stringify({ name, args }),
    });
    showShellOut(res);
  } catch (e) {
    toast("Script failed: " + e.message);
  }
}

// Per-demo task name + seed description for the example chips.
const DEMO_TASKS = {
  stock: "Check MSFT Stock Price",
  expense: "Weekly Expense Report",
  fabric: "Build a Fabric Data Pipeline",
};
const DEMO_SEEDS = {
  stock: "Open a browser and check the MSFT stock price, then report it back",
  expense: "Collect receipts, categorize them, and submit a weekly expense report",
  fabric:
    "Build a Microsoft Fabric pipeline: ingest CSVs from OneLake, clean them, load a lakehouse table, then run it",
};

// ---------- wire up ----------
document.querySelectorAll(".chip").forEach((chip) =>
  chip.addEventListener("click", () => {
    document.querySelectorAll(".chip").forEach((c) => c.classList.remove("active"));
    chip.classList.add("active");
    state.demo = chip.dataset.demo;
    state.schema = null;
    state.taskName = DEMO_TASKS[state.demo] || "";
    $("simTask").value = state.demo;
    $("desc").value = DEMO_SEEDS[state.demo] || "";
    // Selection made in panel 1 -> show that task's skill dynamically.
    loadSkillReport(state.taskName);
  })
);

// Detail (granularity) segmented control.
document.querySelectorAll("#detailSeg .seg-btn").forEach((btn) =>
  btn.addEventListener("click", () => {
    document.querySelectorAll("#detailSeg .seg-btn").forEach((b) => b.classList.remove("active"));
    btn.classList.add("active");
    state.detail = btn.dataset.detail;
    state.schema = null; // re-ground with the new granularity on next generate/start
  })
);

document.querySelectorAll(".mode-tab").forEach((tab) =>
  tab.addEventListener("click", () => setMode(tab.dataset.mode))
);
$("chatSend").addEventListener("click", sendChat);
$("chatText").addEventListener("keydown", (e) => {
  if (e.key === "Enter") sendChat();
});

// Editing the description invalidates any previously generated plan.
$("desc").addEventListener("input", () => {
  state.schema = null;
});

$("generateBtn").addEventListener("click", generate);
$("startBtn").addEventListener("click", startSession);
$("simBtn").addEventListener("click", simulate);
$("viewJsonBtn").addEventListener("click", viewJson);
$("promptBtn").addEventListener("click", viewPrompt);
$("exportBtn").addEventListener("click", exportSkill);
$("deployBtn").addEventListener("click", deploySkill);
$("runBtn").addEventListener("click", () => openRunner(state.taskName));
$("closeJson").addEventListener("click", () => ($("jsonModal").hidden = true));
$("jsonModal").addEventListener("click", (e) => {
  if (e.target.id === "jsonModal") $("jsonModal").hidden = true;
});
$("closeRun").addEventListener("click", () => ($("runModal").hidden = true));
$("runModal").addEventListener("click", (e) => {
  if (e.target.id === "runModal") $("runModal").hidden = true;
});
$("closeLife").addEventListener("click", () => ($("lifecycleModal").hidden = true));
$("lifecycleModal").addEventListener("click", (e) => {
  if (e.target.id === "lifecycleModal") $("lifecycleModal").hidden = true;
});
$("runPlayBtn").addEventListener("click", playRun);
$("runModalInputs").addEventListener("keydown", (e) => {
  if (e.key === "Enter") playRun();
});
document.querySelectorAll(".bp-actions .btn[data-decision]").forEach((b) =>
  b.addEventListener("click", () => decide(b.dataset.decision))
);
$("editRunBtn").addEventListener("click", editAndRun);

// View nav (Studio / Debrief) with lazy Mermaid rendering.
function setView(view) {
  document.querySelectorAll(".view-tab").forEach((t) =>
    t.classList.toggle("active", t.dataset.view === view)
  );
  $("studioView").hidden = view !== "studio";
  $("debriefView").hidden = view !== "debrief";
  $("libraryView").hidden = view !== "library";
  if (view === "debrief" && !window.__mermaidRendered && window.__mermaid) {
    window.__mermaidRendered = true;
    window.__mermaid.run({ querySelector: ".mermaid" }).catch(() => {});
  }
  if (view === "library") loadLibrary();
}
document.querySelectorAll(".view-tab").forEach((t) =>
  t.addEventListener("click", () => setView(t.dataset.view))
);

loadHealth();
loadMcpTools();
loadModels();
resetSkillPanel();
$("newSessionBtn").addEventListener("click", newSession);
$("modelSelect").addEventListener("change", (e) => (state.model = e.target.value));
$("fabricTestBtn").addEventListener("click", fabricSelftest);
$("shellRunBtn").addEventListener("click", runShellCommand);
$("shellCmd").addEventListener("keydown", (e) => {
  if (e.key === "Enter") runShellCommand();
});
